eventFinderApp/urls.py
from django.urls import path
from . import views
#from rest_framework.authtoken import views

app_name = 'eventFinderApp'
urlpatterns = [
    path('test', views.test),
    # event-finder/
    path('', views.IndexView.as_view(), name='index'),
    # event-finder/1
    path('<int:pk>/', views.EventView.as_view(), name='event'),
    # event-finder/my-account
    path('my-account/', views.account, name='account'),
    # event-finder/event_creator_form
    path('event_creator_form/', views.add_event, name='event_creator_form'),
    #event_creator_form
    #path(r'api-auth-token/', views.obtain_auth_token),
    #tokens
]

eventFinderProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from rest_framework import routers
from eventFinderApp import viewsets
from rest_framework.authtoken import views
from users import viewsets as UserViewsets

router = routers.DefaultRouter()
router.register(r'events', viewsets.EventViewSet)
router.register(r'users', UserViewsets.CustomUserViewSet)


urlpatterns = [
    path('event-finder/', include('eventFinderApp.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    #path('register/', views.Register.as_view(), name='register'), #tagged this one out
    path('api/', include(router.urls)),
    path('users/', include('users.urls')),
    path(r'api-auth-token/', views.obtain_auth_token),
    

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # users/1
    path('<int:pk>/', login_required(views.AccountView.as_view()), name='account'),
]

eventFinderApp/models.py
from django.db import models
from django.forms import ModelForm
from django.conf import settings


class Event(models.Model):
    title = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    venue = models.CharField(max_length=200)
    start_time = models.DateTimeField('start time and date')
    end_time = models.DateTimeField('end time and date')
    categories = models.ManyToManyField("Category", related_name = 'events')
    host = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
  first_name = models.CharField(max_length=20)
  #surname = models.CharField(max_length=50)
  join_date =  models.DateTimeField

  def __str__(self):
    return self.email

eventFinderApp/forms.py
from django.forms import ModelForm
from .models import Event, Category

class CreateEventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['title', 
        'location', 
        'venue', 
        'start_time', 
        'end_time', 
        'categories']

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

  class Meta(UserCreationForm):
    model = CustomUser
    fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

  class Meta:
    model = CustomUser
    fields = ('username', 'email')

eventFinderApp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.shortcuts import render
from .forms import CreateEventForm
from django.urls import reverse_lazy
from .models import Event

def test(request):
    return HttpResponse(b"hello world")

class IndexView(generic.ListView):
    template_name = 'eventFinderApp/index.html'
    context_object_name = 'events_list'

    def get_queryset(self):
        '''Return the events.'''
        return Event.objects.all()

class ReturnView(generic.ListView):
    template_name = 'eventFinderApp/index.html'
    context_object_name = 'events_list'

    def get_queryset(self):
        '''Return the events.'''
        return Event.objects.all()


class EventView(generic.DetailView):
    model = Event
    template_name = 'eventFinderApp/event.html'


def account(request):
    return render(request, 'eventFinderApp/account.html')

class EventCreatorView(generic.DetailView):
    form_class = CreateEventForm
    success_url = reverse_lazy('login')
    template = 'eventFinderApp/event_creator_form.html'
    
#     def get(self, request):
#         form = CreateEventForm
#         context = {'form': CreateEventForm}
#         template = 'eventFinderApp/event_creator_form.html'
#         return render(request, template, context)

def add_event(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CreateEventForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # return HttpResponseRedirect('/thanks/')
            form.save()
            return HttpResponseRedirect('/event-finder/thanks/')
        return render(request, 'eventFinderApp/event_creator_form.html', {'CreateEventForm': form})
    # if a GET (or any other method) we'll create a blank form
    else:
        form = CreateEventForm()
        return render(request, 'eventFinderApp/event_creator_form.html', {'CreateEventForm': form})

users/views.py
from django.views import generic
from .models import CustomUser


class AccountView(generic.DetailView):
    model = CustomUser
    template_name = 'users/account.html'
    context_object_name = 'user_profile'

eventFinderApp/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>EventFinda</title>
        <meta name="description" content="">
        <meta name="author" content="Nina K.">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}">
    </head>

    <body>
        <header>
            <div>
                <h1>EventFinda</h1>
                <h2>Find free events near you!</h2>
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %}{% endblock %}
    </body>
</html>

eventFinderApp/templates/eventFinderApp/account.html
 {% extends "base.html" %}
{% block content %}
<h2>Hello, {{ event.title }}</h2>
{% endblock %}

eventFinderApp/templates/eventFinderApp/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>EventFinda</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}">
    </head>

    <body>
        <header>
            <div>
                <h1>EventFinda</h1>
                <h2>Find free events near you!</h2>
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %}{% endblock %}
    </body>
</html>

eventFinderApp/templates/eventFinderApp/detailsBox.html
<div class="details-box">
    <a href="{% url 'eventFinderApp:event' event.id %}">
        <p>{{ event.title }}</p>
        <p>{{ event.start_time }}</p>
        {% for category in event.categories.all %}
            <p>{{ category.name }}</p>
        {% endfor %}
    </a>
</div>

eventFinderApp/templates/eventFinderApp/event.html
{% extends "base.html" %}

{% block content %}

<h2>{{ event.title }}</h2>

<p>{{ event.venue}} | {{ event.location }}</p>
<p></p>
<p>Starts at: {{ event.start_time }}</p>
<p>Ends at: {{ event.end_time }}</p>
{% for category in event.categories.all %}
    <p>Category: {{ category.name }}</p>
{% endfor %}
<p>Host: {{ event.host }}</p>
{% endblock %}

eventFinderApp/templates/eventFinderApp/event_creator_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h3> Add a new event!</h3>
  <form action="" method="post">
    {% csrf_token %}
    {{ CreateEventForm | crispy }}
    <input type="submit" value="submit" >
  </form>
{% endblock %}

eventFinderApp/templates/eventFinderApp/index.html
{% extends "base.html" %}

{% block content %}

    <a href="{% url 'eventFinderApp:event_creator_form' %}"><button id="new-event">+ Create new event</button></a>
    <h3>See what's on!</h3>
    {% if events_list %}
        {% for event in events_list %}
            {% include "./detailsBox.html" with event=event %}
        {% endfor %}
    {% else %}
        <p>No events are available.</p>
    {% endif %}

{% endblock %}

templates/nav.html
<nav>
    <a href="{% url 'eventFinderApp:index' %}">Home</a>
    <a href="{% url 'eventFinderApp:account' %}">My Account</a>
</nav>
{% if user.is_authenticated %}
    <p>Hi {{ user.username }}</p>
    <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
    <p><a href="{% url 'login' %}">login</a></p>
{% endif %}

users/templates/userbase.html
{% if user.is_authenticated %}
    <p>Hi {{ user.username }}</p>
    <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
    <p><a href="{% url 'login' %}">login</a></p>
{% endif %}